name: My First Work FLow

on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v5
      
    - name: welcome message
      run: echo "My First Github Action Job"
    - name: List File
      run: ls
    - name: Read File
      run: cat README.md

    

