name: Upload Down Load Artifacts

on: push
jobs: 
   build_jobs_1:
     runs-on: ubuntu-latest
     steps:
      - name: install Cowsay Program
        run: sudo apt-get install cowsay -y
      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON ....RAWR" >> dragon.txt
      - name: Upload dragon.txt File
        uses: actions/upload-artifact@v4
        with:
          name: dragon-txt-file
          path: dragon.txt

   test_jobs_2:
     needs: build_jobs_1
     runs-on: ubuntu-latest
     steps:
      - name: Download dragon.txt File
        uses: actions/download-artifact@v4
        with:
         name: dragon-txt-file
    
      - name: Test File Exist
        run: grep -i "dragon" dragon.txt
   deploys_jobs_3:
    needs: [build_jobs_1,test_jobs_2]
    runs-on: ubuntu-latest
    steps:
       - name: Download dragon.txt File
         uses: actions/download-artifact@v4
         with:
          name: dragon-txt-file

       - name: Read File
         run: cat dragon.txt
       - name: Deploy
         run: echo Deploying.....
